version: "2"
services:
  listings-report:
    image: tebieto/autoscout24-listing-report:v1.0.0
    container_name: listings-report
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - SYNC=yes
      - PORT=5000
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PGDATABASE=testdb
      - PGDATABASEPROD=
      - PGHOST=listings-db
      - NODE_ENV=development
    volumes:
      - ./server/build/uploads/csv:/app/server/build/uploads/csv
    depends_on:
      - test-db
  test-db:
    container_name: test-db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test-db
    volumes:
      - listings-data:/var/lib/postgresql/data
volumes:
  listings-data:
