version: "2"
services:
  test-app:
    image: tebieto/autoscout24-listing-report:v1.0.0
    container_name: test-app
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - SYNC=yes
      - PORT=5000
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - PGDATABASE=autoscout24
      - PGHOST=test-db
      - NODE_ENV=development
    volumes:
      - ./server/build/uploads/csv:/app/server/build/uploads/csv
    depends_on:
      - test-db
  test-db:
    container_name: test-db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autoscout24
    volumes:
      - test-data:/var/lib/postgresql/pg
volumes:
  test-data:
